# Generated by Django 5.2.5 on 2026-03-03 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DocumentType',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255, unique=True)),
                        ('description', models.TextField(blank=True, default='')),
                        ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                        ('is_active', models.BooleanField(default=True)),
                    ],
                ),
                migrations.CreateModel(
                    name='PickupSlot',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('date', models.DateField(unique=True)),
                        ('morning_slots', models.IntegerField(default=10)),
                        ('afternoon_slots', models.IntegerField(default=10)),
                        ('is_blocked', models.BooleanField(default=False)),
                        ('reason', models.CharField(blank=True, default='', max_length=255)),
                    ],
                ),
                migrations.CreateModel(
                    name='Strand',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100, unique=True)),
                        ('description', models.TextField(blank=True, default='')),
                    ],
                ),
                migrations.AddField(
                    model_name='filerequest',
                    name='no_accountabilities',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='filerequest',
                    name='passkey',
                    field=models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                migrations.AddField(
                    model_name='filerequest',
                    name='pickup_date',
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='filerequest',
                    name='pickup_time',
                    field=models.CharField(blank=True, max_length=50, null=True),
                ),
                migrations.AlterField(
                    model_name='filerequest',
                    name='id',
                    field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.AlterField(
                    model_name='filerequest',
                    name='strand',
                    field=models.CharField(blank=True, default='', max_length=100),
                ),
                migrations.AlterField(
                    model_name='staff',
                    name='id',
                    field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
                migrations.CreateModel(
                    name='AuditLog',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('action', models.CharField(max_length=255)),
                        ('details', models.TextField(blank=True)),
                        ('timestamp', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.CreateModel(
                    name='ProcessedDocument',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('document_type', models.CharField(max_length=100)),
                        ('file', models.FileField(upload_to='processed_docs/')),
                        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                        ('notes', models.TextField(blank=True, default='')),
                        ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_documents', to='request_backend.filerequest')),
                        ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.AddField(
                    model_name='filerequest',
                    name='strand_type',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request_backend.strand'),
                ),
                migrations.CreateModel(
                    name='Student',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('lrn_number', models.CharField(max_length=20, unique=True)),
                        ('first_name', models.CharField(max_length=100)),
                        ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                        ('last_name', models.CharField(max_length=100)),
                        ('suffix', models.CharField(blank=True, default='', max_length=20)),
                        ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                        ('birthdate', models.DateField()),
                        ('year_graduated', models.CharField(max_length=10)),
                        ('email', models.EmailField(max_length=254)),
                        ('phone_number', models.CharField(max_length=20)),
                        ('permanent_address', models.TextField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('strand_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request_backend.strand')),
                    ],
                ),
                migrations.AddField(
                    model_name='filerequest',
                    name='student',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='request_backend.student'),
                ),
                migrations.CreateModel(
                    name='StudentDocument',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('document_type', models.CharField(max_length=100)),
                        ('file', models.FileField(upload_to='student_docs/')),
                        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                        ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='request_backend.filerequest')),
                    ],
                ),
                migrations.CreateModel(
                    name='StudentMasterDocument',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('document_type', models.CharField(max_length=100)),
                        ('file', models.FileField(upload_to='student_master_docs/')),
                        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='request_backend.student')),
                    ],
                ),
            ],
            database_operations=[]
        ),
    ]
