# Generated by Django 5.2.5 on 2026-03-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_backend', '0003_remove_filerequest_birthdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupslot',
            name='afternoon_slots',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='pickupslot',
            name='morning_slots',
            field=models.IntegerField(default=5),
        ),
    ]
